###  ||| 29 percent || 31+30+31+31+28+31 = 182 DAYS (6months)

### EVERY TIME 
#### RESET DATABASE &  RESTART KERNAL & CLAER OUTPUT

In [1]:
import pandas as pd
import MySQLdb
import numpy as np
import time
import datetime 
import random
import matplotlib.pyplot as plt
%matplotlib inline 
import statistics 
import requests
from sympy import *
from sympy.solvers import solve
from sympy.parsing.sympy_parser import parse_expr
# ____________________________________________________________________________________________________   

'''
##  PRIORITY TABLE
'''
class ListTable(list):
    """ Overridden list class which takes a 2-dimensional list of 
        the form [[1,2,3],[4,5,6]], and renders an HTML Table in 
        IPython Notebook. """
    
    def _repr_html_(self):
        html = ["<table>"]
        for row in self:
            html.append("<tr>")
            
            for col in row:
                html.append("<td>{0}</td>".format(col))
            
            html.append("</tr>")
        html.append("</table>")
      
        return ''.join(html)
 # ____________________________________________________________________________________________________   
    
"""
## CONVERSING  UNIT (kW) >>  BILL (bath)
"""
def bill(allpow,Ft):
    
    t1 = 3.2484      # rate_1
    t2 = 4.2218      # rate_2
    t3 = 4.4217      # rate_3
    ser = 38.22      # service_charge
 
    ## Fundamental parameter      
    if allpow <= 0:
        bath = 0
    elif 0 <= allpow <= 150:
        bath = allpow*t1
    elif  151 <= allpow <= 400:
        power = allpow-150
        bath_1 = 150*t1
        bath_2 = power*t2
        bath = bath_1+bath_2
    else:
        power = allpow-150
        bath_1 = 150*t1
        power = power-250
        bath_2 = 250*t2
        bath_3 = power*t3
        bath = bath_1+bath_2+bath_3   
    service_price = 38.22  #permonth (fixed)   
    ## FT -33.2 satang/unit
    FT_price = allpow*Ft
    ## VAT 7%
    VAT_price = ((service_price+bath)+FT_price)*0.07
    bill = bath+service_price+FT_price+VAT_price
    return round(bill,2)
 # ____________________________________________________________________________________________________   

"""
## CONVERSING  BILL (bath) >>  UNIT (kW) >> 
"""
def inbill(bath,Ft):
    
    t1 = 3.2484      # rate_1
    t2 = 4.2218      # rate_2
    t3 = 4.4217      # rate_3
    ser = 38.22      # service_charge  
    u = symbols('u')
    test_1 = solve(Eq((u*t1)+ser+(u*Ft)+(0.07*((u*t1)+ser))+(0.07*(u*Ft)),bath))
    test_2 = solve(Eq((150*t1)+((u-150)*t2)+ser+(u*Ft)+(0.07*((150*t1)+((u-150)*t2)+ser))+(0.07*(u*Ft)),bath))
    test_3 = solve(Eq((150*t1)+(250*t2)+((u-400)*t3)+ser+(u*Ft)+(0.07*((150*t1)+(250*t2)+((u-400)*t3)+ser))+(0.07*(u*Ft)),bath))
    if 1 <=  test_1[0] <= 150:
        unit = test_1[0]
    elif 151 <=  test_2[0] <=  400:
        unit = test_2[0]
    else:
        unit = test_3[0]
    return (round(unit))
 # ____________________________________________________________________________________________________   

"""
## CHECKING  The ENDING POSITION OF EACH APPLIANCES
"""
def end_air(j): 
    check = 1  
    m_air = j+1   
    while (check == 1):
        while df1.aircont[ m_air] > 0 and m_air < (96*182)-1:
            m_air += 1
        check = 0
    return  m_air

def end_com(j): 
    check = 1  
    m_com = j+1   
    while (check == 1):
        while df1.computer[m_com] > 0 and m_com < (96*182)-1:
            m_com += 1  
        check = 0
    return  m_com

def end_elec(j): 
    check = 1  
    m_elec = j+1   
    while (check == 1):
        while df1.elec_thermo[m_elec] > 0 and m_elec < (96*182)-1:
            m_elec += 1  
        check = 0
    return  m_elec

def end_hair(j): 
    check = 1  
    m_hair = j+1   
    while (check == 1):
        while df1.hair_dryer[m_hair] > 0 and m_hair < (96*182)-1:
            m_hair += 1  
        check = 0
    return  m_hair

def end_iphon(j): 
    check = 1  
    m_iphon = j+1   
    while (check == 1):
        while df1.iphonecharger[ m_iphon] > 0 and m_iphon < (96*182)-1:
            m_iphon += 1  
        check = 0
    return  m_iphon

def end_fan(j): 
    check = 1  
    m_fan = j+1   
    while (check == 1):
        while df1.fan[m_fan] > 0 and m_fan < (96*182)-1:
            m_fan += 1  
        check = 0
    return  m_fan

def end_tv(j): 
    check = 1  
    m_tv = j+1   
    while (check == 1):
        while df1.tv[m_tv] > 0 and m_tv < (96*182)-1 :
            m_tv += 1  
        check = 0
    return  m_tv

def end_water(j): 
    check = 1  
    m_water = j+1   
    while (check == 1):
        while df1.water_heater[m_water] > 0 and m_water < (96*182)-1:
            m_water += 1  
        check = 0
    return  m_water
 # ____________________________________________________________________________________________________   

"""
## CHECKING  The STATE OF APPLIANCES 
"""    
def state(j,m_air,m_com, m_elec,m_hair,m_iphon, m_fan ,m_tv, m_water) :
    if j <= m_air:
        ans1 = 18    
    else:
        ans1 = 0
    if j <= m_com:
        ans2 = df1.computer[j]
    else:
        ans2 = 0
    if j <= m_elec:
        ans3 = df1.elec_thermo[j]
    else:
        ans3 = 0
    if j <= m_hair:
        ans4 = df1.hair_dryer[j]
    else:
        ans4 = 0
    if j <= m_iphon:
        ans5 = df1.iphonecharger[j]
    else:
        ans5 = 0
    if j <= m_fan:
        ans6 = df1.fan[j]
    else:
        ans6 = 0
    if j <= m_tv:
        ans7 = df1.tv[j]
    else:
        ans7 = 0
    if j <= m_water:
        ans8 = df1.water_heater[j]
    else:
        ans8 = 0

    k = ans1+ans2+ans3+ans4+ans5+ans6+ans7+ans8
#     print "substact k watt out from watt = ",k,"watt    ||||||" ,ans1,ans2,ans3,ans4,ans5,ans6,ans7,ans8
    return (ans1,ans2,ans3,ans4,ans5,ans6,ans7,ans8,k) 
 # ____________________________________________________________________________________________________   

"""
## PREDICTION 
"""        
def initial_trend(series, slen):
    sum = 0.0
    for i in range(slen):
        sum += float(series[i+slen] - series[i]) / slen
    return sum / slen

def triple_exponential_smoothing(series, slen, alpha, beta, gamma, n_preds):
    result = []
    seasonals = initial_seasonal_components(series, slen)
    for i in range(len(series)+n_preds):
        if i == 0: # initial values
            smooth = series[0]
            trend = initial_trend(series, slen)
            result.append(series[0])
            continue
        if i >= len(series): # we are forecasting
            m = i - len(series) + 1
            result.append((smooth + m*trend) + seasonals[i%slen])
        else:
            val = series[i]
            last_smooth, smooth = smooth, alpha*(val-seasonals[i%slen]) + (1-alpha)*(smooth+trend)
            trend = beta * (smooth-last_smooth) + (1-beta)*trend
            seasonals[i%slen] = gamma*(val-smooth) + (1-gamma)*seasonals[i%slen]
            result.append(smooth+trend+seasonals[i%slen])
    return result

def initial_seasonal_components(series, slen):
    seasonals = {}
    season_averages = []
    n_seasons = int(len(series)/slen)
    # compute season averages
    for j in range(n_seasons):
        season_averages.append(sum(series[slen*j:slen*j+slen])/float(slen))
    # compute initial values
    for i in range(slen):
        sum_of_vals_over_avg = 0.0
        for j in range(n_seasons):
            sum_of_vals_over_avg += series[slen*j+i]-season_averages[j]
        seasonals[i] = sum_of_vals_over_avg/n_seasons
    return seasonals
 # ____________________________________________________________________________________________________   

"""
## FITTING PARAMETERS FOR PREDICTION
""" 
from sklearn.metrics import mean_squared_error
def fittingparameter(data_y,j):
    count_alpha = 0
    count_beta = 0
    count_gamma = 0
    alpha = float(0)
    beta = float(0)
    gamma = float(0)
    index_alpha =[]
    index_beta =[]
    index_gamma = []
    act = j
    data = data_y
    pred_no = 1
    ramda = 0.1
    MSE_holtload = []    
    ##############################################################
    ### ?????????????????????????????????????????????????????????? DATABASE
    query_last = "SELECT Timestamp,total_watt FROM thesis.Prac_device29 WHERE Timestamp = '%s' ;"% (time_b_last[act])
    print query_last
    df1 = pd.read_sql(query_last, conn)
    while (alpha <= float(1)):
        count_alpha += 1
        beta = float(0)
        while (beta <=float(1)):
            count_beta += 1 
            gamma = float(0)
            while (gamma <= float(1)):
                count_gamma += 1
                pred_h = triple_exponential_smoothing(data,96*7,alpha,beta,gamma,pred_no)
                pred_data = pred_h[len(pred_h)-(pred_no):]                                               
                MSE = mean_squared_error (df1.total_watt, pred_data)   
#                 print MSE              
                MSE_holtload.append(MSE)
                index_alpha.append(alpha)
                index_beta.append(beta)
                index_gamma.append(gamma)     
#                 print index_alpha,index_beta,index_gamma
                gamma += ramda
            beta += ramda
        alpha += ramda  
#     print  count_gamma,count_beta,count_alpha    
    index_MSE = MSE_holtload.index(min(MSE_holtload))
    MSE_min = MSE_holtload[index_MSE]
    alpha = index_alpha[index_MSE]
    beta = index_beta[index_MSE]
    gamma= index_gamma[index_MSE]
#     print "the minimum MSE of prediction =",MSE_min,"by alpha =",alpha,"beta =",beta,"gamma =",gamma
    return (alpha,beta,gamma)
 # ____________________________________________________________________________________________________   

"""
## CHECKING THE STATUS OF APPLIANCES ON THAT TIME
""" 
def appliances(j):
    ############################################################## (day + table_database)
    ### ??????????????????????????????????????????????????????????
    time_b = pd.date_range('2016-10-01 00:14:59', periods=96*d, freq='15T')
    conn = MySQLdb.connect("localhost","conn","hems")
    c = conn.cursor()
    query1 = "SELECT * FROM thesis.load WHERE  Timestamp = '%s'; "% (time_b[j])
#     print "Check status of appliances from"
#     print query1
    df1 = pd.read_sql(query1, conn) 
    
    for row in df1.iterrows():
        index, data = row
        state = data.tolist()
    i = 1
    status = []
    while(i < len(state)-1):
        dict = { 1:'refrigerator',2:'wireless_router',3:'aircont',4:'computer',5:'electrical_thermo',6:'hair_dryer',7:'microwave',8:'iphone_charger',9:'fan',10:'tv',
                11:'washing_machine',12:'iron',13:'rice_cooker',14:'water_heater',15:'light_system'}
        if state[i] != 0:
            a = dict[i]
            status.append(a)
        i +=1  
#     print "NOW !! you are turning ON" ,status ,"=",len(status),"items"
#     print "______________________________________________________________________________________________\n"
    return(state)
 # ____________________________________________________________________________________________________   
    
def notify(msg):
    URL = "https://notify-api.line.me/api/notify"
    ACCESS_TOKEN = "vxm278yAqFQcXbo2DlTbLD7pqO0QWU2McdNbiwhJWwp"
    MESSAGE_FIELD = {"message" : msg}
    LINE_HEADERS = { "Authorization": "Bearer " + ACCESS_TOKEN }
    try:
        response = requests.post( url=URL,headers=LINE_HEADERS,data=MESSAGE_FIELD)
#         print("Response HTTP Status Code: {status_code}".format( status_code=response.status_code))
    except requests.exceptions.RequestException:
        print("HTTP Request failed")

In [2]:
# Set paremeters
j = 0
d = 183  ################################
pred_no = 1
z  = 0 
trinker = [0,0,0,0,0,0,0,0]
batt = float(2.900*1000)     ## SIZE OF BATTERY  2.9 kW 
k = 0
all_power = []
sum_power = []
sum_p = []
sum_pv = []
sum_pvconsumption = []
sum_batt = []
sum_battconsumption = []
sum_grid= []
sum_gridconsumption = []
h = 0

ans_air = 0 
ans_com = 0 
ans_elec = 0 
ans_hair = 0 
ans_iphon = 0 
ans_fan = 0
ans_tv = 0
ans_water = 0
m_air = 0
m_com = 0
m_elec = 0
m_hair = 0
m_iphon = 0
m_fan = 0
m_tv = 0   
m_water = 0
minbatt = batt * 0.2        ## PERIOD OF  BATTERY  USING  2.9*0.2 = 580 - 2900
maxbatt = batt
effi = float(1.04)            ##  EFFICIENTCY OF CHARGING  BATTERY  = 96%
levelbatt = []
levelbatt.append(float(batt))  ####################################################
pv_consumption = []
batt_consumption = []
grid_consumption = []
overpv = float(0)
sum_overpv = float(0)
charging_watt = float(0)
count_active = 0 
count_air = 0
count_fan = 0
count_tv = 0
count_com = 0
count_iphon = 0
count_elec = 0
count_hair = 0
count_water = 0
 
sum_check =[]
sum_ch1 =[]
sum_ch2 =[]
sum_ch3 =[]
sum_ch4 =[]
sum_ch5 =[]
sum_ch6 =[]
sum_ch7 =[]
sum_ch8 =[]

change_percent =  float(1)

# Connect MYSQL
conn= MySQLdb.connect("localhost","conn","hems","power")
c = conn.cursor()

# Read the data of lastest month 
################################################## DATA  +DAY
query0 = "SELECT Timestamp,total_watt FROM thesis.load WHERE Timestamp >= '2016-09-01 00:14:59' AND  Timestamp <= '2016-09-30 23:59:59';"
df = pd.read_sql(query0, conn)   
print "\n"
print "Total unit consumption in the last month equal to",df.total_watt.sum()/1000,"kW"
last_bill = bill(df.total_watt.sum()/1000,-0.048)    
print "The lastest elctrical bill is about",last_bill,"bath with Ft = -0.048"
print "\n______________________________________________________________________________________________\n"
   
# x = raw_input('What is about Ft in the next month?',)
# Ft = float(x)
Ft = -0.048    
y = raw_input('How about expected price in electrical bill do you want?')
target_price = float(y)

print "\n______________________________________________________________________________________________"    
print "\nThe expected price in the next electrical bill is about",target_price,"bath with Ft =", Ft
discount = (last_bill-target_price)/last_bill *100
discount_fix = discount
print "To compare with the lastest bill is equal to",round(discount,2),"% cut-off"
target_unit = inbill(target_price,Ft)
print "Total available unit consumption in the next month equal to",target_unit,"kW or unit"
print "______________________________________________________________________________________________\n"


# Show the priority of 15 appliances
name = ['refrigerator','wireless_router','aircont','computer','electrical_thermo','hair_dryer','microwave','iphone_charger','fan','tv','washing_machine','iron','rice_cooker','water_heater','light_system']
types = ['Type1 : always turn on [Dont control]','Type1 : always turn on','Type2 : turn on oncetime&everyday','Type2 : turn on oncetime&everyday','Type2 : turn on oncetime&everyday','Type2 : turn on oncetime&everyday'
        ,'Type2 : turn on oncetime&everyday','Type2 : turn on oncetime&everyday','Type3 : turn on manytime(1-3) in everyday','Type3 : turn on manytime(1-3) in everyday','Type4 : turn on oncetime in someday'
        ,'Type4 : turn on oncetime in someday','Type4 : turn on oncetime in someday','Type5 : turn on manytime(1-3) in someday','Type6 : monitor power consuming [Dont control]']
prior = ['x','x','1','4','6','7','9','5','2','3','12','11','10','9','x']
table = ListTable()
table.append(['the 15 appliances','Type of appliances','the priority'])
for i in xrange(15):
    x = name[i]
    y = types[i]
    z = prior[i]
    table.append([x, y ,z])
    
print "\n"

table

Total unit consumption in the last month equal to 370.1870531 kW
The lastest elctrical bill is about 1537.91 bath with Ft = -0.048

______________________________________________________________________________________________


______________________________________________________________________________________________

The expected price in the next electrical bill is about 1091.0 bath with Ft = -0.048
To compare with the lastest bill is equal to 29.06 % cut-off
Total available unit consumption in the next month equal to 270.0 kW or unit
______________________________________________________________________________________________

[['the 15 appliances', 'Type of appliances', 'the priority'],
 ['refrigerator', 'Type1 : always turn on [Dont control]', 'x'],
 ['wireless_router', 'Type1 : always turn on', 'x'],
 ['aircont', 'Type2 : turn on oncetime&everyday', '1'],
 ['computer', 'Type2 : turn on oncetime&everyday', '4'],
 ['electrical_thermo', 'Type2 : turn on oncetime&everyday', '6'],
 ['hair_dryer', 'Type2 : turn on oncetime&everyday', '7'],
 ['microwave', 'Type2 : turn on oncetime&everyday', '9'],
 ['iphone_charger', 'Type2 : turn on oncetime&everyday', '5'],
 ['fan', 'Type3 : turn on manytime(1-3) in everyday', '2'],
 ['tv', 'Type3 : turn on manytime(1-3) in everyday', '3'],
 ['washing_machine', 'Type4 : turn on oncetime in someday', '12'],
 ['iron', 'Type4 : turn on oncetime in someday', '11'],
 ['rice_cooker', 'Type4 : turn on oncetime in someday', '10'],
 ['water_heater', 'Type5 : turn on manytime(1-3) in someday', '9'],
 ['light_system', 'Type6 : monitor power consuming [Dont control]', 'x']]

In [ ]:
d = 183
charging_watt  = float(0)
############################## DAY
time_a_last = pd.date_range('2016-09-01 00:14:59', periods=96*d, freq='15T')
time_b_last = pd.date_range('2016-09-30 23:59:59', periods=(96*d)+1, freq='15T')

############################## DAY
time_a = pd.date_range('2016-10-01 00:00:00', periods=96*d, freq='15T')
time_b = pd.date_range('2016-10-01 00:14:59', periods=96*d, freq='15T')

conn = MySQLdb.connect("localhost","conn","hems")
c = conn.cursor()

############################## DATA
query_empty = """truncate table thesis.Prac_main29""" 
c.execute(query_empty)
print "table thesis.Prac_main29 are Empty!!! \n"

############################## DATA
query_last = "SELECT * FROM thesis.Prac_device29 WHERE  Timestamp >= '%s' AND Timestamp <= '%s'; "% (time_a_last[j],time_b_last[j])
df_last  = pd.read_sql(query_last, conn)

### DATABASE OPENING DEVICE *****
############################## DATA
query1 = "SELECT * FROM thesis.load WHERE  Timestamp >= '%s' AND Timestamp <= '%s'; "% (time_a[0],time_b[(96*d)-1])
df1 = pd.read_sql(query1, conn)

### DATABASE PV *****
############################## DAY
query = "SELECT Timestamp,PV FROM thesis.PV WHERE Timestamp>='%s'AND Timestamp<='%s'; "%('2016-10-01 00:00:00','2017-03-31 23:59:59')
df = pd.read_sql(query, conn)
df['PV'] = ((df.PV/10)*3)

### DATABASE PLATTERN *****
query_plattern = "SELECT * FROM thesis.plattern_re WHERE  Timestamp >= '%s' AND Timestamp <= '%s'; "% ('2016-09-03 23:59:59','2017-30-31 23:59:59')
df_plattern  = pd.read_sql(query_plattern, conn)

while ( j <= (96*d) -1):
    if (j == 0 or j==2976  or j==5856  or j == 8832  or j == 11808  or j == 14496  or j == 17471):
        sum_check.append(count_air+count_fan+count_tv+count_com+count_iphon+count_elec+count_hair+count_water)
        sum_ch1.append(count_air)
        sum_ch2.append(count_fan)
        sum_ch3.append(count_tv)
        sum_ch4.append(count_com)
        sum_ch5.append(count_iphon)
        sum_ch6.append(count_elec)
        sum_ch7.append(count_hair)
        sum_ch8.append(count_water)
        
        count_active = 0 
        count_air = 0
        count_fan = 0
        count_tv = 0
        count_com = 0
        count_iphon = 0
        count_elec = 0
        count_hair = 0
        count_water = 0
        
       #     print j,
    print "\ndata at :" , j,">>>", time_b[j]
#     print "______________________________________________________________________________________________\n",
    query_last = "\nSELECT Timestamp,total_watt FROM thesis.Prac_device29 WHERE Timestamp>='%s' AND Timestamp<='%s'; "%(time_a_last[j],time_b_last[j])
    print query_last
    df_last = pd.read_sql(query_last, conn)
    conn.commit()
    data_y = df_last['total_watt'].values.tolist()   
    ans_fiting = fittingparameter(data_y,j)
    query_last_new = "SELECT Timestamp,total_watt FROM thesis.Prac_device29 WHERE Timestamp>='%s' AND Timestamp<='%s';"%(time_a_last[j],time_b_last[j])
    query_last_new_1 = "SELECT Timestamp,total_watt FROM thesis.Prac_device29 WHERE Timestamp = '%s' ;"% (time_b_last[j+1])
    print "______________________________________________________________________________________________"
    print "\n",query_last_new  
    print query_last_new_1
    print "BY USE alpha =",ans_fiting[0],"beta =",ans_fiting[1],"gamma =",ans_fiting[2]
    df_last_new = pd.read_sql(query_last_new, conn)
    conn.commit()
    data_y = df_last_new['total_watt'].values.tolist()     
    pred_h = triple_exponential_smoothing(data_y, 96*7, ans_fiting[0], ans_fiting[1], ans_fiting[2],1)
    pred_data = pred_h[len(pred_h)-(pred_no):]   
    pred_watt = abs(pred_data[0])
    target = pred_watt*(1-(discount/100))
    print "predicted watt is ",pred_watt ,"watt ||||| targeted watt at t is ",target,"watt by discount",discount,"watt"
    print "______________________________________________________________________________________________\n"

    if (df.PV[j] != 0):
        if (levelbatt[j] == maxbatt):
            batt_t = levelbatt[j] - minbatt
            watt = df1.total_watt[j] - k
            if (df.PV[j] > watt):
                pv_consumption.append(float(watt))
                batt_consumption.append(float(0))
                grid_consumption.append(float(0))
                levelbatt.append(float(levelbatt[j]))
                sub = target - float(0)
                overpv = df.PV[j] - watt
                sum_overpv += overpv
            else:
                lefted_pv = watt-df.PV[j]
                pv_consumption.append(float(df.PV[j]))
                if (batt_t > lefted_pv):
                    batt_consumption.append(float(lefted_pv))
                    grid_consumption.append(float(0))
                    levelbatt.append(float(levelbatt[j]-lefted_pv))
                    sub = target - float(0)
                else:
                    lefted_batt = lefted_pv - batt_t
                    batt_consumption.append(float(batt_t))
                    grid_consumption.append(float(lefted_batt))
                    levelbatt.append(float(levelbatt[j]-batt_t))
                    sub = target - lefted_batt     
                                           
        else:
            batt_t = levelbatt[j] - minbatt
            watt = df1.total_watt[j] - k
            if (df.PV[j] > watt):
                pv_consumption.append(float(watt))
                batt_consumption.append(float(0))
                grid_consumption.append(float(0))
                charging_watt = df.PV[j] - watt
                missing_watt = (maxbatt - levelbatt[j])*effi
                if (charging_watt > missing_watt):
                    charging_watt = missing_watt /effi
                    overpv = df.PV[j] - watt - missing_watt
                else:
                    charging_watt = charging_watt /effi
                    overpv = 0
                levelbatt.append(float(levelbatt[j]+(charging_watt)))
                sub = target - float(0)
                sum_overpv += overpv   
            else:
                lefted_pv = watt-df.PV[j]
                pv_consumption.append(float(df.PV[j]))
                if (batt_t > lefted_pv):
                    batt_consumption.append(float(lefted_pv))
                    grid_consumption.append(float(0))
                    levelbatt.append(float(levelbatt[j]-lefted_pv))
                    sub = target - float(0)
                else:
                    lefted_batt = lefted_pv - batt_t
                    batt_consumption.append(float(batt_t))
                    grid_consumption.append(float(lefted_batt))
                    levelbatt.append(float(levelbatt[j]-batt_t))
                    sub = target - lefted_batt                          
    else :
        if (levelbatt[j] > minbatt):
            batt_t = levelbatt[j] - minbatt
            watt = df1.total_watt[j] - k 
            if (batt_t > watt):
                pv_consumption.append(float(0))
                batt_consumption.append(float(watt))
                grid_consumption.append(float(0))
                levelbatt.append(float(levelbatt[j]-watt))
                sub = target - float(0)
            else:
                lefted_batt = watt - batt_t
                pv_consumption.append(float(0))
                batt_consumption.append(float(batt_t))
                grid_consumption.append(float(lefted_batt))
                levelbatt.append(float(levelbatt[j]-batt_t))
                sub = target - float(lefted_batt)                
        else:
            watt = df1.total_watt[j] - k 
            pv_consumption.append(float(0))
            batt_consumption.append(float(0))
            grid_consumption.append(float(watt))
            levelbatt.append(float(levelbatt[j]))
            sub = target -  watt
            
#     print "Consuming watt =",watt       
#     print "PV_CONSUMPTION =",pv_consumption[j]
#     print "BATT_CONSUMPTION =",batt_consumption[j]
#     print "GRID_CONSUMPTION =",grid_consumption[j]
#     print "PREVIOUS LEVELBATT =",levelbatt[j],"||| LEFTED LEVELBATT =",levelbatt[j+1]   
#     print "PV GENERATION =",df.PV[j],"||| BATT_CHARGING =",charging_watt
#     print "______________________________________________________________________________________________\n"
    
    

#     print "||| 15 Minutes Lefted You Consumed power from ""PEA"" about",grid_consumption[j],"watt"   
#     print "||| NOW YOUR ELECTRICAL BILL IS ABOUT",bill((sum(grid_consumption))/1000,Ft),"bath"   
#     print "______________________________________________________________________________________________\n" 
   
    if ( j == 0):
        notify("start Prac main 29% {0} ".format( str(sum_check)))
    if ( j == 97):
        notify("End first day of Prac main 29% change{0}".format(str(discount)))
    if ( j == 96*5):
        notify("Test 5 day of Prac main 29% change{0}".format(str(discount)))        
    if ( j == 2975):
        notify("End first month of Prac main 29% {0} ".format( str(sum_check)))
    if ( j == 17471/2):
        notify("running 50/50 of Prac main 29% {0} ".format( str(sum_check)))
    if ( j == 17471):
        notify("finish Prac main 29% {0} ".format( str(sum_check)))

        
    c.execute("INSERT INTO thesis.Prac_main29 (Timestamp, old_watt, predicted_watt, target_watt,PV_genarator , levelbatt ,overpv,pv_consumption , batt_consumption,grid_consumption,sum_load_watt,watt) VALUES ( %s,  %s,%s, %s, %s, %s, %s,%s, %s, %s, %s, %s)",
              (time_b[j],df1.total_watt[j],pred_watt,target,df.PV[j],levelbatt[j],overpv,pv_consumption[j],batt_consumption[j],grid_consumption[j],pv_consumption[j]+batt_consumption[j]+grid_consumption[j],watt))
    conn.commit()  
  
    check_state = appliances(j) 
   
    c.execute("INSERT INTO thesis.Prac_device29 (Timestamp, refrigerator, wirelessrouter, aircont, computer, elec_thermo, hair_dryer, microwave, iphonecharger,fan,tv,washing_machine, iron, rice_cooker, water_heater,light_system, total_watt) VALUES ( %s, %s,%s, %s,%s, %s,%s, %s,%s, %s,%s, %s,%s, %s,%s, %s,%s)",
              (time_b[j],check_state[1],check_state[2],check_state[3]-ans_air,check_state[4]-ans_com,check_state[5]-ans_elec,check_state[6]-ans_hair,check_state[7],check_state[8]-ans_iphon,check_state[9]-ans_fan,check_state[10]--ans_tv,check_state[11],check_state[12],check_state[13],check_state[14]-ans_water,check_state[15],watt))               
    conn.commit()
       
    all_power.append(watt/1000)
    df_power = pd.DataFrame(all_power)

    ###   [Timestamp, refrigerator, wirelessrouter, aircont, computer, elec_thermo, hair_dryer, microwave, iphonecharger,fan,tv,washing_machine, iron, rice_cooker, water_heater,light_system, total_watt]
    del check_state[13]   # del  rice_cooker
    del check_state[12]   # del iron
    del check_state[11]   # del washing_machine
    del check_state[7]    # del microwave
    del check_state[2]    # del wireless_router
    del check_state[1]    # del refrigerator
    del check_state[0]    # del Timestamp
    del check_state[-1]   # del  total_watt
    del check_state[-1]   # del light_system
    ###   [ aircont, computer, elec_thermo, hair_dryer, iphonecharger,fan,tv, water_heater]
           
    if j == 0:
        sum_sub = sub       
    else :
        sum_sub = sum_sub + sub      
    
    if sum_sub < 0: ##turn OFF devices 
#         print "\n_____________________________  POWER CONSUMPTION IS OVER LIMIT________________________________ "
#         print "\n"
#         print "m_air =",check_state[0] , "m_fan=",check_state[5] , "m_tv =",check_state[6] , "m_com =",check_state[1] , "m_iphon =",check_state[4] , "m_elec=",check_state[2] , "m_hair=",check_state[3] , "m_water =",check_state[7]        
                
        if  check_state[0] > 0 and trinker[0] == 0:  #air
            m_air = end_air(j)-1
            count_air += 1
            
        elif  check_state[5] > 0 and trinker[5] == 0:        
            m_fan = end_fan(j)-1
            count_fan += 1
            
        elif  check_state[6] > 0 and trinker[6] == 0:        
            m_tv = end_tv(j)-1
            count_tv += 1  
            
        elif  check_state[1] > 0 and trinker[1] == 0:
            m_com = end_com(j)-1          
            count_com += 1 
            
        elif  check_state[4] > 0 and trinker[4] == 0:        
            m_iphon = end_iphon(j)-1
            count_iphon += 1
            
        elif  check_state[2] > 0 and trinker[2] == 0:
            m_elec = end_elec(j)-1
            count_elec += 1 
            
        elif  check_state[3] > 0 and trinker[3] == 0:        
            m_hair = end_hair(j)-1                    
            count_hair += 1 
            
        elif check_state[7] > 0 and trinker[7] == 0:        
            m_water = end_water(j)-1
            count_water += 1 
#         else:
#             print "No appliances"
            
        if j <= m_air:
            trinker[0] = 1
        else :
            trinker[0] = 0
            
        if j <= m_com:
             trinker[1] = 1
        else :
            trinker[1] = 0 
            
        if j <= m_elec:
             trinker[2] = 1 
        else :
            trinker[2] = 0  
            
        if j <= m_hair:
             trinker[3] = 1
        else :
            trinker[3] = 0  
            
        if j <= m_iphon:
             trinker[4] = 1 
        else :
            trinker[4] = 0  
            
        if j <= m_fan:
             trinker[5] = 1 
        else :            
            trinker[5] = 0  
            
        if j <= m_tv:
             trinker[6] = 1
        else :
            trinker[6] = 0
            
        if j <= m_water:
             trinker[7] = 1 
        else :
            trinker[7] = 0                
#         print "             ",   m_air   , "           ",   m_fan  , "          ",    m_tv   , "             ",  m_com  , "               ", m_iphon , "            ", m_elec  , "            ",m_hair     , "               ",m_water                 
#         print "             ",trinker[0] , "           ",trinker[5] , "         ",trinker[6] , "             ",trinker[7] , "               ",trinker[4] , "           ",trinker[2] , "            ",trinker[3] , "               ",trinker[7]                 
      
        j += 1  
        k = state(j,m_air,m_com,m_elec ,m_hair,m_iphon, m_fan,m_tv,m_water)
        ans_air = k[0] 
        ans_com = k[1] 
        ans_elec = k[2] 
        ans_hair = k[3] 
        ans_iphon = k[4] 
        ans_fan = k[5]
        ans_tv = k[6] 
        ans_water = k[7] 
        k = k[8]          
    else: 
#         print "\n______________________________ POWER CONSUMPTION IS UNDER LIMIT______________________________ "
        j += 1
        k = state(j, m_air,m_com,m_elec ,m_hair,m_iphon, m_fan,m_tv,m_water)  
        ans_air = k[0] 
        ans_com = k[1] 
        ans_elec = k[2] 
        ans_hair = k[3] 
        ans_iphon = k[4] 
        ans_fan = k[5]
        ans_tv = k[6] 
        ans_water = k[7] 
        k = k[8]
#     print "\n"              
    charging_watt = float(0)     
    overpv =  float(0)     
#     print "                             -------------------------------------                                                            \n"
      
    while ( h < (len(df_power)/96) ) : 
        print """\n. . . . . . . . . . . . . . . . . . . .END DAY at""",h,""". . . . . . . . . . . .. . . . . . . . . . . . . . .\n"""
        
#         print (k*24),"to",(k+1)*24
        sum_p =  df_power[(h*96):((h+1)*96)].sum()
        sum_power.append(sum_p)
        
        sum_pv = sum(pv_consumption[(h*96):((h+1)*96)])
        sum_pvconsumption.append(sum_pv/1000)
        
        sum_batt = sum(batt_consumption[(h*96):((h+1)*96)])
        sum_battconsumption.append(sum_batt/1000)
        
        sum_grid = sum(grid_consumption[(h*96):((h+1)*96)])
        sum_gridconsumption.append(sum_grid/1000)
        
        df_power2 = pd.DataFrame(sum_power)  
        df_power3 = pd.DataFrame(sum_pvconsumption)  
        df_power4 = pd.DataFrame(sum_battconsumption)  
        df_power5 = pd.DataFrame(sum_gridconsumption)           
        result = pd.concat([df_power2, df_power3, df_power4, df_power5], axis=1)
        result.columns = ['Power','PV','BATTERY','PEA']       
        Y = df_plattern.total_watt[h]*(1-(discount_fix/100))
        print Y ,result.PEA[h]
        if (result.PEA[h] < Y):            
            change_percent = Y/result.PEA[h]
            print "change to ",change_percent
            discount = discount/change_percent
        else :            
            print "Not change "
            discount = discount_fix
        print result
        print "Power consuming between" ,time_a[h*96], "to" ,time_b[(h+1)*96-1], "equal to", result.iloc[h]['Power']," kW. -->> equal to",bill(float(result.iloc[h]['PEA']),Ft),"bath"
        print """///////////////////////////////////////////////////////////////////////////////////////////////////////////////\n"""
        h +=1 
 
        
print "-------------YOUR PROGRAM IS DONE-----------------"

table thesis.Prac_main29 are Empty!!!

/usr/local/lib/python2.7/dist-packages/pandas/io/sql.py:1401: Warning: Incorrect datetime value: '2017-30-31 23:59:59' for column 'Timestamp' at row 1
  cur.execute(*args)

data at : 0 >>> 2016-10-01 00:14:59

SELECT Timestamp,total_watt FROM thesis.Prac_device29 WHERE Timestamp>='2016-09-01 00:14:59' AND Timestamp<='2016-09-30 23:59:59';
SELECT Timestamp,total_watt FROM thesis.Prac_device29 WHERE Timestamp = '2016-09-30 23:59:59' ;
______________________________________________________________________________________________

SELECT Timestamp,total_watt FROM thesis.Prac_device29 WHERE Timestamp>='2016-09-01 00:14:59' AND Timestamp<='2016-09-30 23:59:59';
SELECT Timestamp,total_watt FROM thesis.Prac_device29 WHERE Timestamp = '2016-10-01 00:14:59' ;
BY USE alpha = 0.7 beta = 0.1 gamma = 0.4
predicted watt is  315.569179389 watt ||||| targeted watt at t is  223.866139575 watt by discount 29.0595678551 watt
______________________________________________________________________________________________

/usr/local/lib/python2.7/dist-packages/ipykernel/__main__.py:198: Warning: Field 'charging_watt' doesn't have a default value

data at : 1 >>> 2016-10-01 00:29:59

SELECT Timestamp,total_watt FROM thesis.Prac_device29 WHERE Timestamp>='2016-09-01 00:29:59' AND Timestamp<='2016-10-01 00:14:59';
SELECT Timestamp,total_watt FROM thesis.Prac_device29 WHERE Timestamp = '2016-10-01 00:14:59' ;
______________________________________________________________________________________________

SELECT Timestamp,total_watt FROM thesis.Prac_device29 WHERE Timestamp>='2016-09-01 00:29:59' AND Timestamp<='2016-10-01 00:14:59';
SELECT Timestamp,total_watt FROM thesis.Prac_device29 WHERE Timestamp = '2016-10-01 00:29:59' ;
BY USE alpha = 0.8 beta = 0.2 gamma = 0.0
predicted watt is  305.676900453 watt ||||| targeted watt at t is  216.848514148 watt by discount 29.0595678551 watt
______________________________________________________________________________________________


data at : 2 >>> 2016-10-01 00:44:59

SELECT Timestamp,total_watt FROM thesis.Prac_device29 WHERE Timestamp>='2016-09-01 00:44:59' AND Timestamp<='2016-10-01 00:29:59';
SELECT Timestamp,total_watt FROM thesis.Prac_device29 WHERE Timestamp = '2016-10-01 00:29:59' ;
______________________________________________________________________________________________

SELECT Timestamp,total_watt FROM thesis.Prac_device29 WHERE Timestamp>='2016-09-01 00:44:59' AND Timestamp<='2016-10-01 00:29:59';
SELECT Timestamp,total_watt FROM thesis.Prac_device29 WHERE Timestamp = '2016-10-01 00:44:59' ;
BY USE alpha = 0.4 beta = 0.4 gamma = 0.5
predicted watt is  293.326471337 watt ||||| targeted watt at t is  208.087066362 watt by discount 29.0595678551 watt
______________________________________________________________________________________________


data at : 3 >>> 2016-10-01 00:59:59

SELECT Timestamp,total_watt FROM thesis.Prac_device29 WHERE Timestamp>='2016-09-01 00:59:59' AND Timestamp<='2016-10-01 00:44:59';
SELECT Timestamp,total_watt FROM thesis.Prac_device29 WHERE Timestamp = '2016-10-01 00:44:59' ;
______________________________________________________________________________________________

SELECT Timestamp,total_watt FROM thesis.Prac_device29 WHERE Timestamp>='2016-09-01 00:59:59' AND Timestamp<='2016-10-01 00:44:59';
SELECT Timestamp,total_watt FROM thesis.Prac_device29 WHERE Timestamp = '2016-10-01 00:59:59' ;
BY USE alpha = 0.6 beta = 1.0 gamma = 0.1
predicted watt is  189.662407204 watt ||||| targeted watt at t is  134.547331287 watt by discount 29.0595678551 watt
______________________________________________________________________________________________


data at : 4 >>> 2016-10-01 01:14:59

SELECT Timestamp,total_watt FROM thesis.Prac_device29 WHERE Timestamp>='2016-09-01 01:14:59' AND Timestamp<='2016-10-01 00:59:59';
SELECT Timestamp,total_watt FROM thesis.Prac_device29 WHERE Timestamp = '2016-10-01 00:59:59' ;
______________________________________________________________________________________________

SELECT Timestamp,total_watt FROM thesis.Prac_device29 WHERE Timestamp>='2016-09-01 01:14:59' AND Timestamp<='2016-10-01 00:59:59';
SELECT Timestamp,total_watt FROM thesis.Prac_device29 WHERE Timestamp = '2016-10-01 01:14:59' ;
BY USE alpha = 0.3 beta = 0.6 gamma = 0.0
predicted watt is  297.452055116 watt ||||| targeted watt at t is  211.013773323 watt by discount 29.0595678551 watt
______________________________________________________________________________________________


data at : 5 >>> 2016-10-01 01:29:59

SELECT Timestamp,total_watt FROM thesis.Prac_device29 WHERE Timestamp>='2016-09-01 01:29:59' AND Timestamp<='2016-10-01 01:14:59';
SELECT Timestamp,total_watt FROM thesis.Prac_device29 WHERE Timestamp = '2016-10-01 01:14:59' ;
______________________________________________________________________________________________

SELECT Timestamp,total_watt FROM thesis.Prac_device29 WHERE Timestamp>='2016-09-01 01:29:59' AND Timestamp<='2016-10-01 01:14:59';
SELECT Timestamp,total_watt FROM thesis.Prac_device29 WHERE Timestamp = '2016-10-01 01:29:59' ;
BY USE alpha = 0.3 beta = 0.6 gamma = 0.6
predicted watt is  287.555602973 watt ||||| targeted watt at t is  203.993187406 watt by discount 29.0595678551 watt
______________________________________________________________________________________________


data at : 6 >>> 2016-10-01 01:44:59

SELECT Timestamp,total_watt FROM thesis.Prac_device29 WHERE Timestamp>='2016-09-01 01:44:59' AND Timestamp<='2016-10-01 01:29:59';
SELECT Timestamp,total_watt FROM thesis.Prac_device29 WHERE Timestamp = '2016-10-01 01:29:59' ;
______________________________________________________________________________________________

SELECT Timestamp,total_watt FROM thesis.Prac_device29 WHERE Timestamp>='2016-09-01 01:44:59' AND Timestamp<='2016-10-01 01:29:59';
SELECT Timestamp,total_watt FROM thesis.Prac_device29 WHERE Timestamp = '2016-10-01 01:44:59' ;
BY USE alpha = 0.8 beta = 0.4 gamma = 0.1
predicted watt is  177.067872317 watt ||||| targeted watt at t is  125.612713812 watt by discount 29.0595678551 watt
______________________________________________________________________________________________


data at : 7 >>> 2016-10-01 01:59:59

SELECT Timestamp,total_watt FROM thesis.Prac_device29 WHERE Timestamp>='2016-09-01 01:59:59' AND Timestamp<='2016-10-01 01:44:59';
SELECT Timestamp,total_watt FROM thesis.Prac_device29 WHERE Timestamp = '2016-10-01 01:44:59' ;
______________________________________________________________________________________________

SELECT Timestamp,total_watt FROM thesis.Prac_device29 WHERE Timestamp>='2016-09-01 01:59:59' AND Timestamp<='2016-10-01 01:44:59';
SELECT Timestamp,total_watt FROM thesis.Prac_device29 WHERE Timestamp = '2016-10-01 01:59:59' ;
BY USE alpha = 0.9 beta = 0.8 gamma = 0.2
predicted watt is  295.875736072 watt ||||| targeted watt at t is  209.895525782 watt by discount 29.0595678551 watt
______________________________________________________________________________________________


data at : 8 >>> 2016-10-01 02:14:59

SELECT Timestamp,total_watt FROM thesis.Prac_device29 WHERE Timestamp>='2016-09-01 02:14:59' AND Timestamp<='2016-10-01 01:59:59';
SELECT Timestamp,total_watt FROM thesis.Prac_device29 WHERE Timestamp = '2016-10-01 01:59:59' ;
______________________________________________________________________________________________

SELECT Timestamp,total_watt FROM thesis.Prac_device29 WHERE Timestamp>='2016-09-01 02:14:59' AND Timestamp<='2016-10-01 01:59:59';
SELECT Timestamp,total_watt FROM thesis.Prac_device29 WHERE Timestamp = '2016-10-01 02:14:59' ;
BY USE alpha = 0.2 beta = 0.6 gamma = 0.5
predicted watt is  178.408192309 watt ||||| targeted watt at t is  126.563542606 watt by discount 29.0595678551 watt
______________________________________________________________________________________________


data at : 9 >>> 2016-10-01 02:29:59

SELECT Timestamp,total_watt FROM thesis.Prac_device29 WHERE Timestamp>='2016-09-01 02:29:59' AND Timestamp<='2016-10-01 02:14:59';
SELECT Timestamp,total_watt FROM thesis.Prac_device29 WHERE Timestamp = '2016-10-01 02:14:59' ;
______________________________________________________________________________________________

SELECT Timestamp,total_watt FROM thesis.Prac_device29 WHERE Timestamp>='2016-09-01 02:29:59' AND Timestamp<='2016-10-01 02:14:59';
SELECT Timestamp,total_watt FROM thesis.Prac_device29 WHERE Timestamp = '2016-10-01 02:29:59' ;
BY USE alpha = 0.1 beta = 0.9 gamma = 0.0
predicted watt is  289.356556399 watt ||||| targeted watt at t is  205.270791549 watt by discount 29.0595678551 watt
______________________________________________________________________________________________


data at : 10 >>> 2016-10-01 02:44:59

SELECT Timestamp,total_watt FROM thesis.Prac_device29 WHERE Timestamp>='2016-09-01 02:44:59' AND Timestamp<='2016-10-01 02:29:59';
SELECT Timestamp,total_watt FROM thesis.Prac_device29 WHERE Timestamp = '2016-10-01 02:29:59' ;
______________________________________________________________________________________________

SELECT Timestamp,total_watt FROM thesis.Prac_device29 WHERE Timestamp>='2016-09-01 02:44:59' AND Timestamp<='2016-10-01 02:29:59';
SELECT Timestamp,total_watt FROM thesis.Prac_device29 WHERE Timestamp = '2016-10-01 02:44:59' ;
BY USE alpha = 0.5 beta = 0.4 gamma = 0.0
predicted watt is  174.490513808 watt ||||| targeted watt at t is  123.784324547 watt by discount 29.0595678551 watt
______________________________________________________________________________________________


data at : 11 >>> 2016-10-01 02:59:59

SELECT Timestamp,total_watt FROM thesis.Prac_device29 WHERE Timestamp>='2016-09-01 02:59:59' AND Timestamp<='2016-10-01 02:44:59';
SELECT Timestamp,total_watt FROM thesis.Prac_device29 WHERE Timestamp = '2016-10-01 02:44:59' ;
______________________________________________________________________________________________

SELECT Timestamp,total_watt FROM thesis.Prac_device29 WHERE Timestamp>='2016-09-01 02:59:59' AND Timestamp<='2016-10-01 02:44:59';
SELECT Timestamp,total_watt FROM thesis.Prac_device29 WHERE Timestamp = '2016-10-01 02:59:59' ;
BY USE alpha = 0.4 beta = 0.6 gamma = 0.1
predicted watt is  266.745251145 watt ||||| targeted watt at t is  189.230233888 watt by discount 29.0595678551 watt
______________________________________________________________________________________________


data at : 12 >>> 2016-10-01 03:14:59

SELECT Timestamp,total_watt FROM thesis.Prac_device29 WHERE Timestamp>='2016-09-01 03:14:59' AND Timestamp<='2016-10-01 02:59:59';
SELECT Timestamp,total_watt FROM thesis.Prac_device29 WHERE Timestamp = '2016-10-01 02:59:59' ;
______________________________________________________________________________________________

SELECT Timestamp,total_watt FROM thesis.Prac_device29 WHERE Timestamp>='2016-09-01 03:14:59' AND Timestamp<='2016-10-01 02:59:59';
SELECT Timestamp,total_watt FROM thesis.Prac_device29 WHERE Timestamp = '2016-10-01 03:14:59' ;
BY USE alpha = 0.3 beta = 0.0 gamma = 0.4
predicted watt is  190.991789996 watt ||||| targeted watt at t is  135.490401185 watt by discount 29.0595678551 watt
______________________________________________________________________________________________


data at : 13 >>> 2016-10-01 03:29:59

SELECT Timestamp,total_watt FROM thesis.Prac_device29 WHERE Timestamp>='2016-09-01 03:29:59' AND Timestamp<='2016-10-01 03:14:59';
SELECT Timestamp,total_watt FROM thesis.Prac_device29 WHERE Timestamp = '2016-10-01 03:14:59' ;
______________________________________________________________________________________________

SELECT Timestamp,total_watt FROM thesis.Prac_device29 WHERE Timestamp>='2016-09-01 03:29:59' AND Timestamp<='2016-10-01 03:14:59';
SELECT Timestamp,total_watt FROM thesis.Prac_device29 WHERE Timestamp = '2016-10-01 03:29:59' ;
BY USE alpha = 0.1 beta = 0.5 gamma = 0.0
predicted watt is  179.714340686 watt ||||| targeted watt at t is  127.490129909 watt by discount 29.0595678551 watt
______________________________________________________________________________________________


data at : 14 >>> 2016-10-01 03:44:59

SELECT Timestamp,total_watt FROM thesis.Prac_device29 WHERE Timestamp>='2016-09-01 03:44:59' AND Timestamp<='2016-10-01 03:29:59';
SELECT Timestamp,total_watt FROM thesis.Prac_device29 WHERE Timestamp = '2016-10-01 03:29:59' ;
______________________________________________________________________________________________

SELECT Timestamp,total_watt FROM thesis.Prac_device29 WHERE Timestamp>='2016-09-01 03:44:59' AND Timestamp<='2016-10-01 03:29:59';
SELECT Timestamp,total_watt FROM thesis.Prac_device29 WHERE Timestamp = '2016-10-01 03:44:59' ;
BY USE alpha = 0.3 beta = 0.7 gamma = 0.3
predicted watt is  197.740308646 watt ||||| targeted watt at t is  140.277829478 watt by discount 29.0595678551 watt
______________________________________________________________________________________________


data at : 15 >>> 2016-10-01 03:59:59

SELECT Timestamp,total_watt FROM thesis.Prac_device29 WHERE Timestamp>='2016-09-01 03:59:59' AND Timestamp<='2016-10-01 03:44:59';
SELECT Timestamp,total_watt FROM thesis.Prac_device29 WHERE Timestamp = '2016-10-01 03:44:59' ;
______________________________________________________________________________________________

SELECT Timestamp,total_watt FROM thesis.Prac_device29 WHERE Timestamp>='2016-09-01 03:59:59' AND Timestamp<='2016-10-01 03:44:59';
SELECT Timestamp,total_watt FROM thesis.Prac_device29 WHERE Timestamp = '2016-10-01 03:59:59' ;
BY USE alpha = 0.7 beta = 1.0 gamma = 0.1
predicted watt is  231.302679998 watt ||||| targeted watt at t is  164.087120753 watt by discount 29.0595678551 watt
______________________________________________________________________________________________


data at : 16 >>> 2016-10-01 04:14:59

SELECT Timestamp,total_watt FROM thesis.Prac_device29 WHERE Timestamp>='2016-09-01 04:14:59' AND Timestamp<='2016-10-01 03:59:59';
SELECT Timestamp,total_watt FROM thesis.Prac_device29 WHERE Timestamp = '2016-10-01 03:59:59' ;
______________________________________________________________________________________________

SELECT Timestamp,total_watt FROM thesis.Prac_device29 WHERE Timestamp>='2016-09-01 04:14:59' AND Timestamp<='2016-10-01 03:59:59';
SELECT Timestamp,total_watt FROM thesis.Prac_device29 WHERE Timestamp = '2016-10-01 04:14:59' ;
BY USE alpha = 0.4 beta = 0.9 gamma = 0.0
predicted watt is  144.83393343 watt ||||| targeted watt at t is  102.745818268 watt by discount 29.0595678551 watt
______________________________________________________________________________________________


data at : 17 >>> 2016-10-01 04:29:59

SELECT Timestamp,total_watt FROM thesis.Prac_device29 WHERE Timestamp>='2016-09-01 04:29:59' AND Timestamp<='2016-10-01 04:14:59';
SELECT Timestamp,total_watt FROM thesis.Prac_device29 WHERE Timestamp = '2016-10-01 04:14:59' ;
______________________________________________________________________________________________

SELECT Timestamp,total_watt FROM thesis.Prac_device29 WHERE Timestamp>='2016-09-01 04:29:59' AND Timestamp<='2016-10-01 04:14:59';
SELECT Timestamp,total_watt FROM thesis.Prac_device29 WHERE Timestamp = '2016-10-01 04:29:59' ;
BY USE alpha = 0.2 beta = 0.6 gamma = 0.2
predicted watt is  139.439814537 watt ||||| targeted watt at t is  98.9192070149 watt by discount 29.0595678551 watt
______________________________________________________________________________________________


data at : 18 >>> 2016-10-01 04:44:59

SELECT Timestamp,total_watt FROM thesis.Prac_device29 WHERE Timestamp>='2016-09-01 04:44:59' AND Timestamp<='2016-10-01 04:29:59';
SELECT Timestamp,total_watt FROM thesis.Prac_device29 WHERE Timestamp = '2016-10-01 04:29:59' ;
______________________________________________________________________________________________

SELECT Timestamp,total_watt FROM thesis.Prac_device29 WHERE Timestamp>='2016-09-01 04:44:59' AND Timestamp<='2016-10-01 04:29:59';
SELECT Timestamp,total_watt FROM thesis.Prac_device29 WHERE Timestamp = '2016-10-01 04:44:59' ;
BY USE alpha = 0.9 beta = 0.9 gamma = 0.4
predicted watt is  172.649045341 watt ||||| targeted watt at t is  122.477978859 watt by discount 29.0595678551 watt
______________________________________________________________________________________________


data at : 19 >>> 2016-10-01 04:59:59

SELECT Timestamp,total_watt FROM thesis.Prac_device29 WHERE Timestamp>='2016-09-01 04:59:59' AND Timestamp<='2016-10-01 04:44:59';
SELECT Timestamp,total_watt FROM thesis.Prac_device29 WHERE Timestamp = '2016-10-01 04:44:59' ;
______________________________________________________________________________________________

SELECT Timestamp,total_watt FROM thesis.Prac_device29 WHERE Timestamp>='2016-09-01 04:59:59' AND Timestamp<='2016-10-01 04:44:59';
SELECT Timestamp,total_watt FROM thesis.Prac_device29 WHERE Timestamp = '2016-10-01 04:59:59' ;
BY USE alpha = 0.8 beta = 0.4 gamma = 0.9
predicted watt is  175.099245837 watt ||||| targeted watt at t is  124.216161679 watt by discount 29.0595678551 watt
______________________________________________________________________________________________


data at : 20 >>> 2016-10-01 05:14:59

SELECT Timestamp,total_watt FROM thesis.Prac_device29 WHERE Timestamp>='2016-09-01 05:14:59' AND Timestamp<='2016-10-01 04:59:59';
SELECT Timestamp,total_watt FROM thesis.Prac_device29 WHERE Timestamp = '2016-10-01 04:59:59' ;
______________________________________________________________________________________________

SELECT Timestamp,total_watt FROM thesis.Prac_device29 WHERE Timestamp>='2016-09-01 05:14:59' AND Timestamp<='2016-10-01 04:59:59';
SELECT Timestamp,total_watt FROM thesis.Prac_device29 WHERE Timestamp = '2016-10-01 05:14:59' ;
BY USE alpha = 0.4 beta = 0.6 gamma = 0.0
predicted watt is  170.847082573 watt ||||| targeted watt at t is  121.199658684 watt by discount 29.0595678551 watt
______________________________________________________________________________________________


data at : 21 >>> 2016-10-01 05:29:59

SELECT Timestamp,total_watt FROM thesis.Prac_device29 WHERE Timestamp>='2016-09-01 05:29:59' AND Timestamp<='2016-10-01 05:14:59';
SELECT Timestamp,total_watt FROM thesis.Prac_device29 WHERE Timestamp = '2016-10-01 05:14:59' ;
______________________________________________________________________________________________

SELECT Timestamp,total_watt FROM thesis.Prac_device29 WHERE Timestamp>='2016-09-01 05:29:59' AND Timestamp<='2016-10-01 05:14:59';
SELECT Timestamp,total_watt FROM thesis.Prac_device29 WHERE Timestamp = '2016-10-01 05:29:59' ;
BY USE alpha = 0.1 beta = 0.7 gamma = 0.3
predicted watt is  171.498071085 watt ||||| targeted watt at t is  121.661472748 watt by discount 29.0595678551 watt
______________________________________________________________________________________________


data at : 22 >>> 2016-10-01 05:44:59

SELECT Timestamp,total_watt FROM thesis.Prac_device29 WHERE Timestamp>='2016-09-01 05:44:59' AND Timestamp<='2016-10-01 05:29:59';
SELECT Timestamp,total_watt FROM thesis.Prac_device29 WHERE Timestamp = '2016-10-01 05:29:59' ;
______________________________________________________________________________________________

SELECT Timestamp,total_watt FROM thesis.Prac_device29 WHERE Timestamp>='2016-09-01 05:44:59' AND Timestamp<='2016-10-01 05:29:59';
SELECT Timestamp,total_watt FROM thesis.Prac_device29 WHERE Timestamp = '2016-10-01 05:44:59' ;
BY USE alpha = 0.4 beta = 0.9 gamma = 0.0
predicted watt is  154.672079686 watt ||||| targeted watt at t is  109.725041737 watt by discount 29.0595678551 watt
______________________________________________________________________________________________


data at : 23 >>> 2016-10-01 05:59:59

SELECT Timestamp,total_watt FROM thesis.Prac_device29 WHERE Timestamp>='2016-09-01 05:59:59' AND Timestamp<='2016-10-01 05:44:59';
SELECT Timestamp,total_watt FROM thesis.Prac_device29 WHERE Timestamp = '2016-10-01 05:44:59' ;
______________________________________________________________________________________________

SELECT Timestamp,total_watt FROM thesis.Prac_device29 WHERE Timestamp>='2016-09-01 05:59:59' AND Timestamp<='2016-10-01 05:44:59';
SELECT Timestamp,total_watt FROM thesis.Prac_device29 WHERE Timestamp = '2016-10-01 05:59:59' ;
BY USE alpha = 0.1 beta = 0.8 gamma = 0.3
predicted watt is  140.710397701 watt ||||| targeted watt at t is  99.8205642021 watt by discount 29.0595678551 watt
______________________________________________________________________________________________


data at : 24 >>> 2016-10-01 06:14:59

SELECT Timestamp,total_watt FROM thesis.Prac_device29 WHERE Timestamp>='2016-09-01 06:14:59' AND Timestamp<='2016-10-01 05:59:59';
SELECT Timestamp,total_watt FROM thesis.Prac_device29 WHERE Timestamp = '2016-10-01 05:59:59' ;
______________________________________________________________________________________________

SELECT Timestamp,total_watt FROM thesis.Prac_device29 WHERE Timestamp>='2016-09-01 06:14:59' AND Timestamp<='2016-10-01 05:59:59';
SELECT Timestamp,total_watt FROM thesis.Prac_device29 WHERE Timestamp = '2016-10-01 06:14:59' ;

In [4]:
print sum_check
print sum_ch1
print sum_ch2
print sum_ch3
print sum_ch4
print sum_ch5
print sum_ch6
print sum_ch7
print sum_ch8

[0, 107, 128, 105, 200, 15, 0]
[0, 17, 21, 18, 25, 5, 0]
[0, 18, 25, 17, 34, 3, 0]
[0, 18, 21, 16, 35, 2, 0]
[0, 10, 12, 11, 20, 0, 0]
[0, 14, 12, 10, 20, 0, 0]
[0, 20, 19, 15, 26, 5, 0]
[0, 7, 10, 10, 20, 0, 0]
[0, 3, 8, 8, 20, 0, 0]

#